language: java
jdk:
  - oraclejdk8
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" >> ~/.mavenrc
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2"
addons:
    apt:
        packages:      
            - sshpass
            - oracle-java8-installer            
    ssh_known_hosts:
      - 141.115.24.12
before_install:
  - rm ~/.m2/settings.xml
script: bash ./build.sh
after_success: 
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - export SSHPASS=$USER_PWD 
  - sh ./publish.sh
branches:
  only:
    - master
