sudo: required
language: java
dist: trusty
jdk:
- oraclejdk8
before_install:
- rm ~/.m2/settings.xml
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2"
addons:
  apt:
    packages:
    - sshpass
    - oracle-java8-installer
  ssh_known_hosts:
  - 141.115.24.12
  sonarcloud:
    organization: "anrgenstar"
    token:
      secure: "1k1XotYg20QAfK5l11P8CqQ8NtDh5PtN5ZJV2hKR9KvyCuot+ly8MtJYB3CJ7hqh4XFiL1Ap5gY+Guq3XC908Qmj7STtTnowa/Jwb/SYIFckKZHcpuJX5kcN8BYNxPCTi/X1AAWaOMSCJdXiIIcfIhe174dewkoehFyaeS1qpSUlKlsmqh6HjjIGnByQUxeZqHR+umbPU2ea0O0bWKWTwFOK36MjPx6Idl5GopGMy+npdG97zjVOnwZw6J91DAIx7UKQJBlvTTITD/twUARd5FN6TJSPxIvcH1hWi9IKR+jR423KVqt2DnTLqmIU1m66o5qCSbUgtc4M1BSxJiv/EQsfIk8EndpwSFQqGVJrdMMHcCnXLune6uWDavjYC/dGYyDfPOgbJOLtqdrl7ysEKPJFg4SKI1WSDul3Y4kUT/ESWVmfZbQYwWP3oLwjYl0hHXS48quDUc0skYf1dO9bhuMHKDzFJnG0vAg4Ms4ecobQKGxqjlT4x7HrKjcGsOW4SbFvtJYThSmkp7W5RALiI2JUi1TxFL0d7AHZILlMZtMv4JB6o5pO/4BwvSJdTqZkFqS9wYtavjo8f7eTXgGi2y+ontJT1Q8zCyruuAOBtrqt0fgVKlHrkO86e8oPnrSpnVtkls4jPJ1vUd0mi4LGWhhbXojnkUtEB7TiAGLSrQE=" # encrypted value of your token
script:
  - cd genstar.gamaplugin.parent
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ANRGenstar_genstar.gamaplugin
  - cd -
after_success:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export SSHPASS=$USER_PWD
- sh ./publish.sh
branches:
  only:
  - master
